### PR TITLE
Ds payment type #7

### PR DESCRIPTION
**Pull request by AnupamaGarg**
# Description

This Ticket is for Payment Type. Users can Create new Payment Type when they are logged in.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

git fetch --all
git checkout DS_PaymentType_#7
Run 
then click on My Settings
then create new PaymentType

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by gradyrobbins — APPROVED** [review]
Dolly this is wonderful work.  Thank you!

**Review by allisonkatecollins — APPROVED** [review]
Looks great! Nice work

**Review by loetek — APPROVED** [review]
The function looks great I approve. I would recommend changing the label to be more descriptive.

**Comment by AnupamaGarg** [comment]
I have changed the Column name from Description To Bank Name and Account Number to Bank Account Number.

**Pull request merged**
