### PR TITLE
Ac product detail

### PR DESCRIPTION
**Pull request by allisonkatecollins**
Closes Ticket #2 

# Description

Created ProductDetails.cshtml view within Views/Home, and there is an identical Details.cshtml view within Views/Products. Functionally it will look the same as the previous ticket, but the routing is dynamic and set up for better future functionality. Also added user authentication code to the ProductsController.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

git fetch --all 
git checkout ac-product-detail
run Bangazon
check that each product listed on the home page links to the product's respective details view

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by allisonkatecollins** [comment]
The details views are technically different files, but the content is identical... Not sure if that matters. From a user perspective at least, the tickets have been fulfilled.

**Review by gradyrobbins — APPROVED** [review]
Thanks, Allison. great work! 👍

**Review by loetek — APPROVED** [review]
It is fantastic, thank you!

**Review by ColleenWoolsey — APPROVED** [review]
I'd shop here - Appreciate easy to follow PR style

**Pull request merged**
